# GoReleaser configuration
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: git-workspace
    main: .
    binary: git-workspace
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/yejune/git-workspace/cmd.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: git-workspace
    repository:
      owner: yejune
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/yejune/git-workspace"
    description: "Manage nested git repositories with independent push capability"
    license: "MIT"
    install: |
      bin.install "git-workspace"
    test: |
      system "#{bin}/git-workspace", "--version"
